apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "optimizer.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "optimizer.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.schedule | quote }}
  timeZone: {{ .Values.timeZone | quote }}
  concurrencyPolicy: {{ .Values.concurrencyPolicy }}
  successfulJobsHistoryLimit: {{ .Values.history.successfulJobs }}
  failedJobsHistoryLimit: {{ .Values.history.failedJobs }}
  startingDeadlineSeconds: {{ .Values.startingDeadlineSeconds }}
  jobTemplate:
    spec:
      backoffLimit: {{ .Values.job.backoffLimit }}
      ttlSecondsAfterFinished: {{ .Values.job.ttlSecondsAfterFinished }}
      template:
        metadata:
          labels:
            {{- include "optimizer.labels" . | nindent 12 }}
        spec:
          serviceAccountName: {{ include "optimizer.fullname" . }}
          restartPolicy: Never
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          containers:
            - name: optimizer
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              securityContext:
                {{- toYaml .Values.containerSecurityContext | nindent 16 }}
              resources:
                {{- toYaml .Values.resources | nindent 16 }}