{{- if hasKey .Values "rbac" }}
{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "optimizer.fullname" . }}-reader
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "optimizer.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "optimizer.fullname" . }}
    namespace: {{ .Values.namespace.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "optimizer.fullname" . }}-reader
{{- end }}
{{- end }}