apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    scrape_configs:
      - job_name: ai-k8s-cost-optimizer
        metrics_path: /metrics
        static_configs:
          - targets:
              - optimizer-metrics.cost-optimizer.svc.cluster.local:8000